name: Print Software Versions

on:
  push:
    branches: [main]

jobs:
  # Виведення версій ПО рівня обробки даних
  data_processing_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Перевірка версії Node.js
        run: node --version
      
      - name: Установка Angular CLI
        run: npm install -g @angular/cli

      - name: Перевірка версії Angular
        run: ng version

      - name: Завантаження та установка Apache Tomcat
        run: |
          wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.58/bin/apache-tomcat-9.0.58.tar.gz
          tar -xvzf apache-tomcat-9.0.58.tar.gz
          chmod +x apache-tomcat-9.0.58/bin/version.sh

      - name: Перевірка версії Apache Tomcat
        run: ./apache-tomcat-9.0.58/bin/version.sh

  # Виведення версій СКБД на рівні доступу даних
  database_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Перевірка версії PostgreSQL
        run: psql --version
